[run]
init_cmds = [
	["make"],
	["./npm-registry"]
]

watch_dirs = [
	"server",
	"storage",
	"routes",
	"model",
	"auth",
	"storage-engines",
	"packages"
]
watch_exts = [".go"]
ignore = [".git", "node_modules"]
ignore_files = []

build_delay = 1500
interrupt_timout = 15
graceful_kill = false

cmds = [
	["make"],
	["./npm-registry"]
]

[sync]
listen_addr = ":8080"
remote_addr = ":8080"
